FROM postgis/postgis:14-3.1
RUN apt-get update && apt-get install -y postgresql-plpython3-$PG_MAJOR
RUN mkdir /io
# Deal with line endings
#RUN apt-get update && apt-get install -y dos2unix
#RUN sudo find /docker-entrypoint-initdb.d -type f -print0 | xargs -0 dos2unix /docker-entrypoint-initdb.d
# set time zone
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# add backup job
#RUN mkdir -p /io/backup_scripts
#COPY ./pgbackup.sh /io/backup_scripts/pg_backup.sh
#RUN chmod +x /io/backup_scripts/pg_backup.sh